#! /usr/bin/env bash

######################################
# This script will fetch the list of python species from Wikipedia and save it to a file
# Usage: ./wikipython.sh
# Author: Skillab Team
# Copyright: This work is licensed under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
######################################

######################################
# Description
# Extracts the list of python species from Wikipedia and saves it to a file
# Globals:
#	 None
# Arguments:
# 	 None
######################################

# Define the URL
URL="https://en.wikipedia.org/wiki/Python_(genus)"

# Fetch the webpage using curl and filter out the python species
curl -s "$URL" | grep -Eo 'title="Python [^"]+' | awk -F\" '{print $2}' > pythons.txt

# Append the count of species to the file
echo "Total species count: $(wc -l < pythons.txt)" >> pythons.txt

# Inform user
echo "Python species extracted and saved to pythons.txt"
