version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: skillab-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  fastapi:
    build:
      context: .
    container_name: skillab-backend
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
